<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="mb-4"><h1 class="h3 section-title fw-bold mb-1">My Orders</h1><p class="text-secondary mb-0">Find previous orders, track active orders, and reorder available items.</p></div>
<div class="row g-3 mb-4">
<?php foreach ([['Total orders',$summary['total_orders'] ?? 0,'bi-receipt'],['Completed',$summary['completed_orders'] ?? 0,'bi-check2-circle'],['Total spent',format_price($summary['total_spent'] ?? 0),'bi-wallet2'],['Active',$summary['active_orders'] ?? 0,'bi-hourglass-split']] as [$label,$value,$icon]): ?><div class="col-6 col-lg-3"><div class="stat-card h-100"><i class="bi <?= esc($icon) ?>"></i><div><div class="text-secondary small"><?= esc($label) ?></div><div class="h4 mb-0 fw-bold"><?= esc((string)$value) ?></div></div></div></div><?php endforeach; ?>
</div>
<form class="surface-card p-3 mb-4" method="get"><div class="row g-3 align-items-end"><div class="col-lg-3"><label class="form-label">Order number</label><input class="form-control" name="q" value="<?= esc($q) ?>" placeholder="Search order #"></div><div class="col-lg-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">All</option><?php foreach (\App\Enums\OrderStatus::cases() as $case): ?><option value="<?= esc($case->value,'attr') ?>" <?= $status===$case->value?'selected':'' ?>><?= esc($case->label()) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label">Type</label><select class="form-select" name="type"><option value="">All</option><option value="pickup" <?= $type==='pickup'?'selected':'' ?>>Pickup</option><option value="delivery" <?= $type==='delivery'?'selected':'' ?>>Delivery</option></select></div><div class="col-lg-2"><label class="form-label">From</label><input class="form-control" type="date" name="from" value="<?= esc($from,'attr') ?>"></div><div class="col-lg-2"><label class="form-label">To</label><input class="form-control" type="date" name="to" value="<?= esc($to,'attr') ?>"></div><div class="col-lg-1"><button class="btn btn-primary w-100" aria-label="Filter"><i class="bi bi-funnel"></i></button></div></div></form>
<div class="table-card table-responsive d-none d-md-block"><table class="table align-middle mb-0"><thead><tr><th>Order</th><th>Date & time</th><th>Type</th><th>Items</th><th>Total</th><th>Payment</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($orders as $order): ?><tr><td class="fw-semibold"><?= esc($order['order_number']) ?></td><td><?= esc(date('M j, Y g:i A',strtotime($order['created_at']))) ?></td><td><?= esc(ucfirst($order['order_type'])) ?></td><td><?= (int)$order['item_count'] ?></td><td class="fw-semibold"><?= format_price($order['total']) ?></td><td><div><?= esc(payment_method_label($order['payment_method'])) ?></div><small class="text-secondary"><?= esc(ucfirst($order['payment_status'])) ?></small></td><td><?= order_status_badge($order['status']) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="<?= base_url('customer/orders/'.$order['id']) ?>">View</a> <button class="btn btn-sm btn-outline-secondary" type="button" data-reorder-order="<?= (int)$order['id'] ?>">Reorder</button></td></tr><?php endforeach; ?></tbody></table></div>
<div class="d-md-none d-grid gap-3"><?php foreach ($orders as $order): ?><article class="surface-card p-3"><div class="d-flex justify-content-between gap-3"><div><div class="fw-bold"><?= esc($order['order_number']) ?></div><small class="text-secondary"><?= esc(date('M j, Y g:i A',strtotime($order['created_at']))) ?></small></div><?= order_status_badge($order['status']) ?></div><div class="row g-2 small mt-2"><div class="col-6">Type: <strong><?= esc(ucfirst($order['order_type'])) ?></strong></div><div class="col-6">Items: <strong><?= (int)$order['item_count'] ?></strong></div><div class="col-6">Payment: <strong><?= esc(ucfirst($order['payment_status'])) ?></strong></div><div class="col-6">Total: <strong><?= format_price($order['total']) ?></strong></div></div><div class="d-flex gap-2 mt-3"><a class="btn btn-sm btn-primary flex-fill" href="<?= base_url('customer/orders/'.$order['id']) ?>">View</a><button class="btn btn-sm btn-outline-secondary flex-fill" type="button" data-reorder-order="<?= (int)$order['id'] ?>">Reorder</button></div></article><?php endforeach; ?></div>
<?php if (!$orders): ?><?= view('components/empty',['icon'=>'bi-receipt','message'=>'No orders match your filters.']) ?><?php endif; ?><div class="mt-3"><?= $pager->links() ?></div>
<?= $this->endSection() ?>
