<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<?php
$steps = ['pending','confirmed','preparing','ready_for_pickup'];
if ($order['order_type']==='delivery') $steps[]='out_for_delivery';
$steps[]='completed';
$historyByStatus=[]; foreach ($history as $entry) { $historyByStatus[$entry['to_status']]=$entry; }
$currentIndex=array_search($order['status'],$steps,true); if ($currentIndex===false) $currentIndex=-1;
?>
<div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><a class="text-decoration-none small" href="<?= base_url('customer/orders') ?>"><i class="bi bi-arrow-left"></i> My orders</a><h1 class="h3 section-title fw-bold mt-2 mb-1"><?= esc($order['order_number']) ?></h1><div><?= order_status_badge($order['status']) ?></div></div><div class="text-lg-end"><div class="text-secondary">Total</div><div class="display-6 fw-bold"><?= format_price($order['total']) ?></div></div></div>
<div class="surface-card p-4 mb-4" data-order-status-tracker data-order-id="<?= (int)$order['id'] ?>" data-order-status="<?= esc($order['status'], 'attr') ?>"><h2 class="h5 fw-bold section-title mb-4">Order progress</h2><div class="order-progress"><?php foreach ($steps as $i=>$step): $enum=\App\Enums\OrderStatus::from($step); $done=$order['status']==='cancelled' ? false : $i <= $currentIndex; ?><div class="order-progress-step <?= $done?'is-done':'' ?>"><div class="order-progress-dot"><i class="bi <?= esc($enum->icon()) ?>"></i></div><div class="order-progress-label"><?= esc($enum->label()) ?></div><small class="text-secondary"><?= isset($historyByStatus[$step]) ? esc(date('g:i A',strtotime($historyByStatus[$step]['created_at']))) : '—' ?></small></div><?php endforeach; ?></div><?php if ($order['status']==='cancelled'): ?><div class="alert alert-danger mt-3 mb-0">This order was cancelled.</div><?php endif; ?></div>
<div class="row g-4"><div class="col-lg-8"><div class="surface-card p-4 mb-4"><h2 class="h5 fw-bold section-title">Items</h2><?php foreach ($items as $item): $addons=json_decode((string)($item['addons_json']??'[]'),true)?:[]; ?><div class="py-3 border-bottom"><div class="d-flex justify-content-between gap-3"><div><strong><?= (int)$item['quantity'] ?> × <?= esc($item['product_name']) ?></strong><?php if($addons): ?><div class="small text-secondary"><?= esc(implode(', ',array_column($addons,'name'))) ?></div><?php endif; ?><?php if(!empty($item['notes'])): ?><div class="small text-secondary">Note: <?= esc($item['notes']) ?></div><?php endif; ?></div><strong><?= format_price($item['line_total']) ?></strong></div></div><?php endforeach; ?><div class="pt-3 ms-auto order-total-breakdown"><div class="d-flex justify-content-between"><span>Subtotal</span><span><?= format_price($order['subtotal']) ?></span></div><div class="d-flex justify-content-between"><span>Discount</span><span>-<?= format_price($order['discount']) ?></span></div><div class="d-flex justify-content-between"><span>Delivery fee</span><span><?= format_price($order['delivery_fee']) ?></span></div><div class="d-flex justify-content-between fw-bold fs-5 border-top pt-2 mt-2"><span>Total</span><span><?= format_price($order['total']) ?></span></div></div></div>
<div class="surface-card p-4"><h2 class="h5 fw-bold section-title">Timeline</h2><?php foreach($history as $entry): ?><div class="d-flex gap-3 py-2 border-bottom"><i class="bi bi-circle-fill small text-primary mt-1"></i><div><div class="fw-semibold"><?= esc(\App\Enums\OrderStatus::tryFrom($entry['to_status'])?->label() ?? $entry['to_status']) ?></div><small class="text-secondary"><?= esc(date('M j, Y g:i A',strtotime($entry['created_at']))) ?><?= $entry['note'] ? ' · '.esc($entry['note']) : '' ?></small></div></div><?php endforeach; ?></div></div>
<div class="col-lg-4"><div class="surface-card p-4 mb-4"><h2 class="h5 fw-bold section-title">Order details</h2><dl class="row small mb-0"><dt class="col-5">Type</dt><dd class="col-7"><?= esc(ucfirst($order['order_type'])) ?></dd><dt class="col-5">Payment</dt><dd class="col-7"><?= esc(payment_method_label($order['payment_method'])) ?> · <?= esc(ucfirst($order['payment_status'])) ?></dd><dt class="col-5">Placed</dt><dd class="col-7"><?= esc(date('M j, Y g:i A',strtotime($order['created_at']))) ?></dd><?php if($order['order_type']==='delivery'): ?><dt class="col-5">Address</dt><dd class="col-7"><?= esc($order['delivery_address'] ?: '—') ?></dd><dt class="col-5">Rider</dt><dd class="col-7"><?= esc($order['rider_name'] ?? 'Not assigned') ?></dd><?php endif; ?></dl></div><div class="surface-card p-4 text-center"><h2 class="h5 fw-bold section-title">Order QR</h2><p class="small text-secondary">Staff can scan this signed code to verify the order.</p><div class="mx-auto" data-qr-code data-qr-value="<?= esc($verificationUrl,'attr') ?>"></div><button class="btn btn-sm btn-outline-secondary mt-3" type="button" data-print-page><i class="bi bi-printer"></i> Print receipt</button></div></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script src="<?= base_url('assets/vendor/qrcode-generator/qrcode.min.js') ?>"></script><script src="<?= base_url('assets/js/qr.js') ?>"></script><?= $this->endSection() ?>
