<?= $this->extend('layouts/main') ?>
<?= $this->section('styles') ?><style media="print">.app-sidebar,.app-topbar,.mobile-bottom-nav,.report-controls,.nav-tabs{display:none!important}.app-main{margin:0!important}.tab-pane{display:block!important;opacity:1!important;margin-bottom:2rem}.surface-card{box-shadow:none!important}</style><?= $this->endSection() ?>
<?= $this->section('content') ?>
<div class="d-flex flex-column flex-lg-row justify-content-between gap-3 mb-4"><div><h1 class="h3 section-title fw-bold">Report center</h1><p class="text-secondary mb-0">Paid sales, orders, inventory, food popularity, and delivery transactions.</p></div><form class="d-flex flex-column flex-sm-row gap-2 report-controls" method="get"><input type="hidden" name="type" value="<?= esc($active,'attr') ?>"><input class="form-control" type="date" name="from" value="<?= esc($from) ?>"><input class="form-control" type="date" name="to" value="<?= esc($to) ?>"><button class="btn btn-primary">Apply</button><button class="btn btn-outline-secondary" type="button" data-print-page><i class="bi bi-printer"></i></button></form></div>
<ul class="nav nav-tabs mb-4 report-controls"><?php foreach(['sales'=>'Sales','orders'=>'Orders','inventory'=>'Inventory','popular'=>'Popular food','deliveries'=>'Deliveries'] as $key=>$label): ?><li class="nav-item"><a class="nav-link <?= $active===$key?'active':'' ?>" href="<?= base_url('admin/reports?type='.$key.'&from='.$from.'&to='.$to) ?>"><?= esc($label) ?></a></li><?php endforeach; ?></ul>
<div class="d-flex justify-content-end mb-3 report-controls"><a class="btn btn-sm btn-outline-primary" href="<?= base_url('admin/reports/export/'.$active.'?from='.$from.'&to='.$to) ?>"><i class="bi bi-download me-1"></i>Export current tab CSV</a></div>

<?php if ($active==='sales'): $s=$sales['summary']; ?>
<div class="row g-3 mb-4"><?php foreach([['Gross sales',$s['gross_sales']],['Discounts',$s['discounts']],['Delivery fees',$s['delivery_fees']],['Net sales',$s['net_sales']],['Average order',$s['average_order_value']]] as [$label,$value]): ?><div class="col-6 col-lg"><div class="stat-card p-3 bg-white"><small class="text-secondary"><?= esc($label) ?></small><div class="h4 fw-bold mb-0"><?= format_price($value) ?></div></div></div><?php endforeach; ?></div>
<div class="surface-card p-4 mb-4"><h2 class="h5 fw-bold">Daily paid sales</h2><canvas data-sales-chart data-labels='<?= esc(json_encode(array_column($sales['daily'],'sale_date')), 'attr') ?>' data-values='<?= esc(json_encode(array_map('floatval',array_column($sales['daily'],'total'))), 'attr') ?>' height="100"></canvas></div>
<div class="row g-4"><?php foreach([['Order type',$sales['byType']],['Payment method',$sales['byPayment']],['Channel',$sales['byChannel']]] as [$title,$rows]): ?><div class="col-lg-4"><div class="surface-card table-card"><div class="p-3"><h2 class="h6 fw-bold mb-0"><?= esc($title) ?></h2></div><table class="table mb-0"><thead><tr><th>Group</th><th>Orders</th><th class="text-end">Sales</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= esc(ucwords(str_replace('_',' ',$r['label']))) ?></td><td><?= (int)$r['orders'] ?></td><td class="text-end"><?= format_price($r['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endforeach; ?></div>
<?php elseif ($active==='orders'): ?>
<div class="row g-3 mb-4"><div class="col-md-4"><div class="stat-card p-4 bg-white"><small>Cancellation rate</small><div class="h3"><?= number_format($ordersReport['cancellationRate'],1) ?>%</div></div></div><div class="col-md-4"><div class="stat-card p-4 bg-white"><small>Avg. preparation</small><div class="h3"><?= number_format($ordersReport['averagePreparationMinutes'],1) ?> min</div></div></div><div class="col-md-4"><div class="stat-card p-4 bg-white"><small>Orders</small><div class="h3"><?= count($ordersReport['rows']) ?></div></div></div></div>
<div class="surface-card table-card"><div class="table-responsive"><table class="table"><thead><tr><th>Order</th><th>Date</th><th>Type</th><th>Status</th><th>Payment</th><th class="text-end">Total</th></tr></thead><tbody><?php foreach($ordersReport['rows'] as $r): ?><tr><td><?= esc($r['order_number']) ?></td><td><?= esc(date('M j, Y g:i A',strtotime($r['created_at']))) ?></td><td><?= esc(ucfirst($r['order_type'])) ?></td><td><?= order_status_badge($r['status']) ?></td><td><?= esc(ucfirst($r['payment_status'])) ?></td><td class="text-end"><?= format_price($r['total']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php elseif ($active==='inventory'): ?>
<div class="row g-3 mb-4"><div class="col-md-6"><div class="stat-card p-4 bg-white"><small>Low stock</small><div class="h3"><?= count($inventoryReport['lowStock']) ?></div></div></div><div class="col-md-6"><div class="stat-card p-4 bg-white"><small>Out of stock</small><div class="h3"><?= count($inventoryReport['outOfStock']) ?></div></div></div></div>
<div class="surface-card table-card"><div class="table-responsive"><table class="table"><thead><tr><th>Product</th><th>Opening</th><th>Stock-in</th><th>Sold</th><th>Restocked</th><th>Adjustments</th><th>Waste</th><th>Closing</th><th>Current</th><th>Reorder</th><th>Stock value</th></tr></thead><tbody><?php foreach($inventoryReport['products'] as $p): $m=$inventoryReport['movements'][(int)$p['id']]??[]; ?><tr><td><?= esc($p['name']) ?></td><td><?= (int)$p['opening_stock'] ?></td><td><?= (int)($m['stock_in']??0) ?></td><td><?= abs((int)($m['sale']??0)) ?></td><td><?= (int)($m['cancel_restock']??0) ?></td><td><?= (int)($m['adjustment']??0) ?></td><td><?= abs((int)($m['waste']??0)) ?></td><td><?= (int)$p['closing_stock'] ?></td><td><?= (int)$p['stock'] ?></td><td><?= (int)$p['reorder_level'] ?></td><td><?= format_price($p['stock_value']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php elseif ($active==='popular'): ?>
<div class="row g-4"><div class="col-lg-6"><div class="surface-card table-card"><div class="p-3"><h2 class="h5 fw-bold">Top sellers</h2></div><table class="table"><thead><tr><th>Product</th><th>Qty</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($popularReport['top'] as $r): ?><tr><td><?= esc($r['product_name']) ?></td><td><?= (int)$r['quantity'] ?></td><td class="text-end"><?= format_price($r['revenue']) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-lg-6"><div class="surface-card table-card"><div class="p-3"><h2 class="h5 fw-bold">Slowest sellers</h2></div><table class="table"><thead><tr><th>Product</th><th>Qty</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($popularReport['slow'] as $r): ?><tr><td><?= esc($r['product_name']) ?></td><td><?= (int)$r['quantity'] ?></td><td class="text-end"><?= format_price($r['revenue']) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="surface-card table-card mt-4"><div class="p-3"><h2 class="h5 fw-bold">Sales by category</h2></div><table class="table"><thead><tr><th>Category</th><th>Qty</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($popularReport['categories'] as $r): ?><tr><td><?= esc($r['category']) ?></td><td><?= (int)$r['quantity'] ?></td><td class="text-end"><?= format_price($r['revenue']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="surface-card table-card mt-4"><div class="p-3"><h2 class="h5 fw-bold">Best-selling add-ons</h2></div><table class="table"><thead><tr><th>Add-on</th><th>Qty</th><th class="text-end">Revenue</th></tr></thead><tbody><?php foreach($popularReport['addons'] as $r): ?><tr><td><?= esc($r['addon_name']) ?></td><td><?= (int)$r['quantity'] ?></td><td class="text-end"><?= format_price($r['revenue']) ?></td></tr><?php endforeach; ?><?php if(!$popularReport['addons']): ?><tr><td colspan="3" class="text-center text-secondary py-4">No add-on sales in this period.</td></tr><?php endif; ?></tbody></table></div>
<?php else: ?>
<div class="surface-card p-4 mb-4"><strong>Average delivery time:</strong> <?= number_format($deliveryReport['averageDeliveryMinutes'],1) ?> minutes</div><div class="surface-card table-card"><div class="table-responsive"><table class="table"><thead><tr><th>Rider</th><th>Total</th><th>Completed</th><th>Cancelled</th><th>Delivery fees</th><th>COD collected</th></tr></thead><tbody><?php foreach($deliveryReport['riders'] as $r): ?><tr><td><?= esc($r['rider']) ?></td><td><?= (int)$r['total'] ?></td><td><?= (int)$r['completed'] ?></td><td><?= (int)$r['cancelled'] ?></td><td><?= format_price($r['delivery_fees']) ?></td><td><?= format_price($r['cod_collected']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php endif; ?>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script src="<?= base_url('assets/vendor/chartjs/chart.umd.min.js') ?>"></script><script src="<?= base_url('assets/js/reports.js') ?>"></script><?= $this->endSection() ?>
