<?= $this->extend('layouts/main') ?>
<?= $this->section('content') ?>
<div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-4"><div><h1 class="h3 section-title fw-bold">Products</h1><p class="text-secondary mb-0">Manage menu prices, stock, images, and availability.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#productModal"><i class="bi bi-plus-lg me-1"></i>New product</button></div>
<div class="surface-card table-card overflow-hidden"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php foreach ($products as $product): ?><tr><td><div class="d-flex align-items-center gap-3"><?php if ($product['image']): ?><img src="<?= media_url($product['image']) ?>" alt="<?= esc($product['name']) ?>" class="rounded" style="width:54px;height:54px;object-fit:cover"><?php else: ?><div class="rounded bg-light p-2" style="width:54px;height:54px"><img src="<?= base_url('assets/img/jrmsu-cafeteria-logo.png') ?>" alt=""></div><?php endif; ?><div><div class="fw-semibold"><?= esc($product['name']) ?></div><small class="text-secondary"><?= esc(mb_strimwidth($product['description'] ?? '',0,52,'…')) ?></small></div></div></td><td><?= esc($product['category_name'] ?? '—') ?></td><td class="fw-semibold"><?= format_price($product['price']) ?></td><td><?= esc($product['stock']) ?></td><td><span class="badge <?= $product['is_available'] ? 'text-bg-success' : 'text-bg-secondary' ?>"><?= $product['is_available'] ? 'Available' : 'Hidden' ?></span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" data-edit-product='<?= esc(json_encode($product), 'attr') ?>'><i class="bi bi-pencil"></i></button><form class="d-inline" data-confirm="Remove this product?" action="<?= base_url('admin/products/'.$product['id'].'/delete') ?>" method="post"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; ?>
<?php if (!$products): ?><tr><td colspan="6"><?= view('components/empty', ['icon'=>'bi-cup-hot','message'=>'Add your first menu product.']) ?></td></tr><?php endif; ?>
</tbody></table></div></div>
<div class="modal fade" id="productModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-scrollable"><form class="modal-content" id="productForm" action="<?= base_url('admin/products') ?>" method="post" enctype="multipart/form-data" data-confirm="Save this product?" data-confirm-title="Save product" data-confirm-label="Save"><?= csrf_field() ?><div class="modal-header"><h2 class="modal-title h5">Product details</h2><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-7"><label class="form-label">Product name</label><input class="form-control" name="name" required></div><div class="col-md-5"><label class="form-label">Category</label><select class="form-select" name="category_id" required><option value="">Select category</option><?php foreach ($categories as $category): ?><option value="<?= $category['id'] ?>"><?= esc($category['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description"></textarea></div><div class="col-sm-6 col-lg-3"><label class="form-label">Price</label><input class="form-control" type="number" step="0.01" min="0" name="price" required></div><div class="col-sm-6 col-lg-3"><label class="form-label">Stock</label><input class="form-control" type="number" min="0" name="stock" required></div><div class="col-lg-6"><label class="form-label">Product image</label><input class="form-control" type="file" name="image" accept="image/png,image/jpeg,image/webp"></div><div class="col-12 d-flex gap-4"><div class="form-check"><input class="form-check-input" type="checkbox" value="1" name="is_available" id="available" checked><label class="form-check-label" for="available">Available</label></div><div class="form-check"><input class="form-check-input" type="checkbox" value="1" name="is_featured" id="featured"><label class="form-check-label" for="featured">Featured</label></div></div></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" type="submit">Save product</button></div></form></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?><script>document.querySelectorAll('[data-edit-product]').forEach(b=>b.addEventListener('click',()=>{const p=JSON.parse(b.dataset.editProduct),f=document.getElementById('productForm');f.action='/admin/products/'+p.id;['name','category_id','description','price','stock'].forEach(n=>f.elements[n].value=p[n]??'');f.elements.is_available.checked=Number(p.is_available)===1;f.elements.is_featured.checked=Number(p.is_featured)===1;bootstrap.Modal.getOrCreateInstance(document.getElementById('productModal')).show()}));</script><?= $this->endSection() ?>
